packages:
  - 'apps/*'
  - 'packages/*'
  - 'skills/phase-*/*'
  - 'mcp/servers/*'

catalogs:
  shared:
    react: ^18.0.0
    react-dom: ^18.0.0
    typescript: ^5.0.0
    eslint: ^8.0.0
    prettier: ^3.0.0
